from dataclasses import dataclass
from datetime import timedelta
from typing import Any, Iterable, Mapping, Literal
from ._access import EngineView

@dataclass(frozen=True)
class RuntimeSource:
    source_id: str
    domain: Literal['surface', 'groundwater']
    cell: int
    flow_m3_s: float = ...
    concentrations: Mapping[str, float] = ...
    species_rates: Mapping[str, float] = ...
    heat_w: float = ...
    until_seconds: float | None = ...

@dataclass(frozen=True)
class SourceReceipt:
    requested_m3: float
    applied_m3: float
    rejected_m3: float
    requested_heat_j: float
    applied_heat_j: float
    rejected_heat_j: float
    requested_species: dict[str, float]
    applied_species: dict[str, float]
    last_applied_m3_s: float
    last_interval_seconds: float
    @property
    def rejected_species(self) -> dict[str, float]: ...
    @property
    def limiter_reasons(self) -> tuple[str, ...]: ...

@dataclass(frozen=True)
class BoundaryReceipt(SourceReceipt):
    @property
    def limiter_reasons(self) -> tuple[str, ...]: ...

class Coupling(EngineView):
    @property
    def provider_id(self) -> str: ...
    def __init__(self, owner: Any, provider: str = ...) -> None: ...
    def for_provider(self, name: str) -> Coupling: ...
    @property
    def surface(self) -> DomainSources: ...
    @property
    def groundwater(self) -> DomainSources: ...
    def apply_frame(self, frame: CouplingFrame) -> None: ...
    @property
    def capabilities(self) -> dict[str, bool]: ...
    def set_sources(self, records: Iterable[RuntimeSource]) -> None: ...
    def advance_to(self, seconds: float) -> timedelta: ...

class DomainSources(EngineView):
    def __init__(self, owner: Any, domain: Literal['surface', 'groundwater'], provider: str = ...) -> None: ...
    @property
    def water_totals(self) -> dict[str, float]: ...
    def set_source(self, cells: Any, flow_m3_s: Any = ..., *, source_id: str = ...,
                   concentrations: Mapping[str, Any] | None = ...,
                   species_rates: Mapping[str, Any] | None = ..., heat_w: Any = ...,
                   until_seconds: float | None = ...) -> None: ...
    def clear_source(self, source_id: str = ..., cell: int | None = ...) -> None: ...
    def source_receipt(self, source_id: str = ..., cell: int = ...) -> SourceReceipt: ...
    def set_boundary(self, cell: int, edge: int, kind: int, value: float,
                     concentrations: Mapping[str, float] | None = ...) -> None: ...
    def clear_boundary(self, cell: int, edge: int) -> None: ...
    def boundary_flow(self, cell: int, edge: int) -> float: ...

    def set_boundaries(self, records: Iterable[RuntimeBoundary]) -> None: ...
    def set_forcings(self, records: Iterable[RuntimeForcing]) -> None: ...
    def source_receipts(self, cells: Iterable[int], source_id: str = ...) -> list[SourceReceipt]: ...
    def boundary_receipt(self, cell: int, edge: int) -> BoundaryReceipt: ...
    def infiltration_receipt(self, cell: int) -> BoundaryReceipt: ...
    def species_ledger(self, species: str) -> dict[str, float]: ...

@dataclass(frozen=True)
class RuntimeBoundary:
    domain: Literal['surface', 'groundwater']
    cell: int
    edge: int
    kind: int
    value: float = ...
    concentrations: Mapping[str, float] = ...

@dataclass(frozen=True)
class RuntimeForcing:
    channel: Literal['rainfall', 'evaporation', 'infiltration', 'rain_quality']
    cell: int = ...
    rate_m_s: float = ...
    mode: Literal['replace', 'add', 'clear'] = ...
    concentrations: Mapping[str, float] | None = ...
    until_seconds: float | None = ...

@dataclass(frozen=True)
class RuntimeClear:
    source_id: str
    domain: Literal['surface', 'groundwater']
    cell: int = ...

@dataclass(frozen=True)
class CouplingFrame:
    sources: Iterable[RuntimeSource] = ...
    boundaries: Iterable[RuntimeBoundary] = ...
    forcings: Iterable[RuntimeForcing] = ...
    clears: Iterable[RuntimeClear] = ...
