from __future__ import annotations
from typing import Any, Mapping
from ._coupling import DomainSources, SourceReceipt

from dataclasses import dataclass
from collections.abc import Iterator, MutableMapping
from typing import Any
import numpy as np
from numpy.typing import NDArray
from ._enums import (CellScope, GroundwaterVariable, GroundwaterLedger,
                     GroundwaterZone, GroundwaterSpeciesLedger)

@dataclass(frozen=True)
class AquiferRow:
    scope: CellScope
    tag: str
    cell: int
    ks: float
    zs: float
    theta_s: float
    theta_r: float
    alpha: float

@dataclass(frozen=True)
class AquiferNode:
    node: str
    cell: int
    kc: float
    dc: float
    area: float
    locate: bool
    exchange: bool
    automatic: bool

from ._gw_transport import GroundwaterTransport

class AquiferOptions(MutableMapping[str, str]):
    """Text options using the native INP key/value spellings."""
    def __init__(self, owner: Any) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: object) -> None: ...
    def set_process_options(self, *, et: str, link: str, wilting: str | float = ..., authored: bool = ...) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...


class Groundwater:
    @property
    def transport(self) -> GroundwaterTransport: ...
    def __init__(self, owner: Any) -> None: ...
    @property
    def options(self) -> AquiferOptions: ...
    @property
    def rows(self) -> tuple[AquiferRow, ...]: ...
    def add_row(self, scope: CellScope, ks: float, zs: float, theta_s: float, theta_r: float, alpha: float, *, tag: str = ..., cell: int = ...) -> None: ...
    def row_property(self, index: int, key: str) -> float: ...
    def set_row_property(self, index: int, key: str, value: float) -> None: ...
    def remove_row(self, index: int) -> None: ...
    @property
    def nodes(self) -> tuple[AquiferNode, ...]: ...
    def add_node(self, node: str, cell: int, kc: float, dc: float, area: float = ...) -> None: ...
    def remove_node(self, index: int) -> None: ...
    def set_node_exchange(self, index: int, enabled: bool) -> None: ...
    @property
    def active(self) -> bool: ...
    @property
    def dimensions(self) -> tuple[int, int]: ...
    def cell(self, cell: int, variable: GroundwaterVariable) -> float: ...
    def cells(self, variable: GroundwaterVariable) -> NDArray[np.float64]: ...
    def column(self, cell: int) -> NDArray[np.float64]: ...
    def ledger(self, term: GroundwaterLedger) -> float: ...
    @property
    def continuity_error(self) -> float: ...
    @property
    def tier_histogram(self) -> NDArray[Any]: ...
    @property
    def species(self) -> tuple[str, ...]: ...
    @property
    def sources(self) -> DomainSources: ...
    def set_water_source(self, cells: Any, flow_m3_s: Any, **kwargs: Any) -> None: ...
    def set_heat_source(self, cells: Any, heat_w: Any, *, source_id: str = ..., until_seconds: float | None = ...) -> None: ...
    def set_species_source(self, cells: Any, species_rates: Mapping[str, Any], *, source_id: str = ..., until_seconds: float | None = ...) -> None: ...
    def clear_source(self, source_id: str = ..., cell: int | None = ...) -> None: ...
    def source_receipt(self, source_id: str = ..., cell: int = ...) -> SourceReceipt: ...
    def set_head_boundary(self, cell: int, edge: int, head_m: float, concentrations: Mapping[str, float] | None = ...) -> None: ...
    def set_flow_boundary(self, cell: int, edge: int, flow_m3_s: float, concentrations: Mapping[str, float] | None = ...) -> None: ...
    def clear_boundary(self, cell: int, edge: int) -> None: ...
    def boundary_flow(self, cell: int, edge: int) -> float: ...
    def boundary_receipt(self, cell: int, edge: int) -> SourceReceipt: ...
    def concentrations(self, zone: GroundwaterZone, species: int) -> NDArray[np.float64]: ...
    def species_ledger(self, species: int, term: GroundwaterSpeciesLedger) -> float: ...
