from __future__ import annotations
from dataclasses import dataclass
from collections.abc import MutableMapping
from typing import Any
import numpy as np
from numpy.typing import NDArray
from ._enums import (CellScope, GroundwaterVariable, GroundwaterLedger,
                     GroundwaterZone, GroundwaterSpeciesLedger)

@dataclass(frozen=True)
class AquiferRow:
    scope: CellScope
    tag: str
    cell: int
    ks: float
    zs: float
    theta_s: float
    theta_r: float
    alpha: float

@dataclass(frozen=True)
class AquiferNode:
    node: str
    cell: int
    kc: float
    dc: float
    area: float
    locate: bool
    exchange: bool
    automatic: bool

from ._gw_transport import GroundwaterTransport

class Groundwater:
    @property
    def transport(self) -> GroundwaterTransport: ...
    def __init__(self, owner: Any) -> None: ...
    @property
    def options(self) -> MutableMapping[str, str]: ...
    @property
    def rows(self) -> tuple[AquiferRow, ...]: ...
    def add_row(self, scope: CellScope, ks: float, zs: float, theta_s: float, theta_r: float, alpha: float, *, tag: str = ..., cell: int = ...) -> None: ...
    def row_property(self, index: int, key: str) -> float: ...
    def set_row_property(self, index: int, key: str, value: float) -> None: ...
    def remove_row(self, index: int) -> None: ...
    @property
    def nodes(self) -> tuple[AquiferNode, ...]: ...
    def add_node(self, node: str, cell: int, kc: float, dc: float, area: float = ...) -> None: ...
    def remove_node(self, index: int) -> None: ...
    def set_node_exchange(self, index: int, enabled: bool) -> None: ...
    @property
    def active(self) -> bool: ...
    @property
    def dimensions(self) -> tuple[int, int]: ...
    def cell(self, cell: int, variable: GroundwaterVariable) -> float: ...
    def cells(self, variable: GroundwaterVariable) -> NDArray[np.float64]: ...
    def column(self, cell: int) -> NDArray[np.float64]: ...
    def ledger(self, term: GroundwaterLedger) -> float: ...
    @property
    def continuity_error(self) -> float: ...
    @property
    def tier_histogram(self) -> NDArray[Any]: ...
    @property
    def species(self) -> tuple[str, ...]: ...
    def concentrations(self, zone: GroundwaterZone, species: int) -> NDArray[np.float64]: ...
    def species_ledger(self, species: int, term: GroundwaterSpeciesLedger) -> float: ...
