"""Type stubs for :mod:`openswmm.engine._heat`."""

from collections.abc import Iterator
from typing import NamedTuple, Union

from ._enums import (
    HeatCloudParam, HeatFluxModule, HeatRadiativeParam, HeatShortwaveMode,
    HeatSolarParam, HeatSourceKind,
)
from ._solver import Solver


_Node = Union[int, str]
_Module = Union[HeatFluxModule, int, str]
_Radiative = Union[HeatRadiativeParam, int, str]
_Solar = Union[HeatSolarParam, int, str]
_Cloud = Union[HeatCloudParam, int, str]
_Source = Union[HeatSourceKind, int, str]


class HeatNodeOverride(NamedTuple):
    source: HeatSourceKind
    node_index: int
    temp_c: float


class _HeatModules:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[HeatFluxModule]: ...
    def __getitem__(self, key: _Module) -> bool: ...
    def __setitem__(self, key: _Module, value: bool) -> None: ...


class _HeatRadiative:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[HeatRadiativeParam]: ...
    def __getitem__(self, key: _Radiative) -> float: ...
    def __setitem__(self, key: _Radiative, value: float) -> None: ...


class _HeatSolar:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[HeatSolarParam]: ...
    def __getitem__(self, key: _Solar) -> float: ...
    def __setitem__(self, key: _Solar, value: float) -> None: ...


class _HeatCloud:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[HeatCloudParam]: ...
    def __getitem__(self, key: _Cloud) -> float: ...
    def __setitem__(self, key: _Cloud, value: float) -> None: ...

    configured: bool
    current: float

    def set_timeseries(self, name: str) -> None: ...
    def clear(self) -> None: ...


class _HeatSources:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[HeatSourceKind]: ...
    def __getitem__(self, key: _Source) -> float: ...
    def __setitem__(self, key: _Source, temp_c: float) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def is_configured(self, source: _Source) -> bool: ...
    def clear(self, source: _Source) -> None: ...
    def effective(self, source: _Source, node: _Node) -> float: ...


class _HeatNodeOverrides:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[HeatNodeOverride]: ...
    def __getitem__(self, row_index: int) -> HeatNodeOverride: ...
    def set(self, source: _Source, node: _Node, temp_c: float) -> None: ...
    def remove(self, row_index: int) -> None: ...


class Heat:
    def __init__(self, solver: Solver) -> None: ...

    enabled: bool
    modules: _HeatModules
    radiative: _HeatRadiative
    shortwave_mode: HeatShortwaveMode
    current_shortwave: float
    solar: _HeatSolar
    solar_sited: bool
    cloud: _HeatCloud
    sources: _HeatSources
    node_overrides: _HeatNodeOverrides

    def set_shortwave_timeseries(self, name: str) -> None: ...
