"""
Hot start files (Pythonic v1 surface)
=====================================

Type stubs for :mod:`openswmm.engine._hotstart`.
"""

from collections.abc import MutableSequence
from datetime import datetime
from os import PathLike
from typing import Any, List, NamedTuple, Optional, Union

from ._solver import Solver


_PathLike = Union[str, PathLike[str]]


class SaveScheduleEntry(NamedTuple):
    when: datetime
    path: str


class HotStart:
    def __init__(self) -> None: ...

    @staticmethod
    def save_from(solver: Solver, path: _PathLike) -> None: ...

    @classmethod
    def open(cls, path: _PathLike) -> "HotStart": ...

    def close(self) -> None: ...
    def __enter__(self) -> "HotStart": ...
    def __exit__(self, *args: Any) -> bool: ...

    def apply(self, solver: Solver) -> None: ...

    sim_datetime: datetime
    crs: Optional[str]
    node_count: int
    link_count: int
    warnings: List[str]

    def set_node_depth(self, node_id: str, depth: float) -> None: ...
    def set_node_head(self, node_id: str, head: float) -> None: ...
    def set_link_flow(self, link_id: str, flow: float) -> None: ...
    def set_link_depth(self, link_id: str, depth: float) -> None: ...
    def set_subcatchment_runoff(self, sub_id: str, runoff: float) -> None: ...

    def __repr__(self) -> str: ...


class SaveSchedule(MutableSequence[SaveScheduleEntry]):
    def __init__(self, solver: Solver) -> None: ...

    def __len__(self) -> int: ...
    def __getitem__(self, idx: Any) -> Any: ...
    def __setitem__(self, idx: Any, value: Any) -> None: ...
    def __delitem__(self, idx: Any) -> None: ...
    def insert(self, idx: int, value: Any) -> None: ...
    def append(self, value: Any) -> None: ...
    def clear(self) -> None: ...
