"""Type stubs for :mod:`openswmm.engine._reactions`."""

from collections.abc import Iterator
from typing import NamedTuple, Optional, Tuple, Union

from ._enums import ReactionExprForm, ReactionScope
from ._solver import Solver


_Key = Union[int, str]


class ReactionHydVar(NamedTuple):
    name: str
    description: str


class ReactionFunction(NamedTuple):
    name: str
    arity: int


class ReactionInitialEntry(NamedTuple):
    is_link: bool
    elem_index: int
    species_index: int
    value: float


class ExpressionDiagnostic(NamedTuple):
    valid: bool
    message: str
    column: int


class ReactionSpecies:
    def __init__(self, solver: Solver, index: int) -> None: ...

    index: int
    name: str
    is_wall: bool
    units: str
    atol: float
    rtol: float
    initial: float
    pipe_expression: Tuple[ReactionExprForm, str]
    tank_expression: Tuple[ReactionExprForm, str]

    def get_expression(self, scope: ReactionScope) -> Tuple[ReactionExprForm, str]: ...
    def set_expression(
        self, scope: ReactionScope, form: ReactionExprForm, expression: str = ...,
    ) -> None: ...


class ReactionCoefficient:
    def __init__(self, solver: Solver, index: int) -> None: ...

    index: int
    name: str
    is_param: bool
    value: float


class ReactionTerm:
    def __init__(self, solver: Solver, index: int) -> None: ...

    index: int
    name: str
    expression: str


class _SpeciesCollection:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[ReactionSpecies]: ...
    def __getitem__(self, key: _Key) -> ReactionSpecies: ...
    def __contains__(self, key: object) -> bool: ...
    def get_index(self, key: _Key) -> int: ...
    def add(
        self, name: str, *, wall: bool = ..., units: str = ...,
        atol: float = ..., rtol: float = ...,
    ) -> ReactionSpecies: ...
    def remove(self, key: _Key) -> None: ...


class _CoefficientCollection:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[ReactionCoefficient]: ...
    def __getitem__(self, key: _Key) -> ReactionCoefficient: ...
    def __contains__(self, key: object) -> bool: ...
    def get_index(self, key: _Key) -> int: ...
    def add(
        self, name: str, *, parameter: bool = ..., value: float = ...,
    ) -> ReactionCoefficient: ...
    def remove(self, key: _Key) -> None: ...


class _TermCollection:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[ReactionTerm]: ...
    def __getitem__(self, key: _Key) -> ReactionTerm: ...
    def __contains__(self, key: object) -> bool: ...
    def get_index(self, key: _Key) -> int: ...
    def add(self, name: str, expr: str) -> ReactionTerm: ...
    def remove(self, key: _Key) -> None: ...


class _InitialQualityRows:
    def __init__(self, solver: Solver) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[ReactionInitialEntry]: ...
    def __getitem__(self, row: int) -> ReactionInitialEntry: ...
    def set(
        self, is_link: bool, elem_index: int, species: _Key, value: float,
    ) -> None: ...
    def remove(self, row: int) -> None: ...


class Reactions:
    def __init__(self, solver: Solver) -> None: ...

    species: _SpeciesCollection
    coefficients: _CoefficientCollection
    terms: _TermCollection
    initial: _InitialQualityRows

    def validate(
        self, expr: str, scope: ReactionScope = ...,
    ) -> ExpressionDiagnostic: ...

    def get_option(self, key: str) -> str: ...
    def set_option(self, key: str, value: str) -> None: ...

    def serialize(self) -> str: ...
    def check_text(self, text: str) -> ExpressionDiagnostic: ...
    def apply_text(self, text: str) -> None: ...
    def save(self, path: Optional[str] = ...) -> None: ...

    @staticmethod
    def hydraulic_variables() -> Tuple[ReactionHydVar, ...]: ...
    @staticmethod
    def functions() -> Tuple[ReactionFunction, ...]: ...
