"""Type stubs for :mod:`openswmm.engine._spatial`."""

from typing import Tuple, Union

import numpy as np

from ._solver import Solver


_Key = Union[int, str]


class Spatial:
    def __init__(self, solver: Solver) -> None: ...

    crs: str

    def node_coord(self, node: _Key) -> Tuple[float, float]: ...
    def set_node_coord(self, node: _Key, x: float, y: float) -> None: ...
    def node_coords(self) -> np.ndarray: ...
    def set_node_coords(self, coords: np.ndarray) -> None: ...

    def link_coord(self, link: _Key) -> Tuple[float, float]: ...
    def set_link_coord(self, link: _Key, x: float, y: float) -> None: ...
    def link_vertices(self, link: _Key) -> np.ndarray: ...
    def set_link_vertices(self, link: _Key, vertices: np.ndarray) -> None: ...

    def subcatchment_coord(self, sub: _Key) -> Tuple[float, float]: ...
    def set_subcatchment_coord(self, sub: _Key, x: float, y: float) -> None: ...
    def subcatchment_polygon(self, sub: _Key) -> np.ndarray: ...
    def set_subcatchment_polygon(self, sub: _Key, polygon: np.ndarray) -> None: ...

    def gage_coord(self, gage: _Key) -> Tuple[float, float]: ...
    def set_gage_coord(self, gage: _Key, x: float, y: float) -> None: ...
