#!/usr/bin/env python3
"""Generate tests/parity/snow/snow_parity.inp — the snow parity deck.

WHY THIS EXISTS
---------------
Seven defects (F1-F7 in plans/transport/SNOW_DIVERGENCE_REGISTER.md) were
fixed in the snow module across four rounds. Not one of the 14 reference decks
in the bit-identity corpus has a [SNOWPACKS] section -- confirmed by grep in
both the S3 and S4 rounds -- so "14/14 byte-identical" was structurally
incapable of observing any of them. This deck closes that hole.

The deck is GENERATED rather than hand-written so that the meteorology is
auditable: every temperature and rainfall value below has a stated reason, and
regenerating must be byte-reproducible (no RNG, no clock, no dict ordering).

WHAT EACH REGIME IS FOR
-----------------------
The met series is built from five named phases, each chosen to drive one part
of the snow path that a defect lived in:

  phase 1  ACCUMULATE   cold + precip   -> snowfall accumulates; packs build
  phase 2  FIRST THAW   warm, dry       -> degree-day melt with NO rain (F1);
                                           free water fills below capacity,
                                           which is exactly F2/F4's regime --
                                           the one with no runoff to look at
  phase 3  REFREEZE     cold + precip   -> cold content, ATI, and NEW SNOW on
                                           a depleted pack, which is the only
                                           way to reach the new-snow ADC index
                                           (`awe`) that F7 lived in
  phase 4  RAIN ON SNOW mild + rain     -> rain onto a partially covered pack
                                           (F3), split by `asc` (F6)
  phase 5  FULL MELT    warming, dry    -> packs deplete to nothing, and the
                                           tail passes through the sub-0.001
                                           inch instant-melt branch (F5)

Run length is 30 days, which also makes the SEASONAL melt constant observable:
`dhm` is rescaled daily by sin(0.0172615*(day-81)), the constant D1 wrongly
"corrected" and S4 restored. Over 30 days the two constants separate by far
more than a byte-identity check needs.

USAGE
    python3 gen_snow_parity.py > snow_parity.inp
"""

import sys

START = "01/01/2026"
DAYS = 30
STEP_H = 3                      # met series interval, hours
N = DAYS * 24 // STEP_H         # rows per series

# --- phase table: (first_day, last_day, air_F, rain_inhr) -------------------
# Values are held flat across each phase and stepped at phase boundaries; a
# flat hold is deliberate, so a movement in the output can be attributed to a
# phase rather than to interpolation.
PHASES = [
    # day span   air F   rain in/hr   what it drives
    (1,  3,      22.0,   0.06),   # ACCUMULATE: well below Stemp -> all snow
    (4,  5,      18.0,   0.00),   # ACCUMULATE: cold and dry; pack sits
    (6,  9,      41.0,   0.00),   # FIRST THAW: degree-day melt, no rain
    (10, 12,     26.0,   0.04),   # REFREEZE: new snow onto a depleted pack
    (13, 14,     30.0,   0.00),   # REFREEZE: at Tbase; cold content, no melt
    (15, 18,     38.0,   0.05),   # RAIN ON SNOW: above Stemp -> liquid
    (19, 21,     35.0,   0.00),   # RAIN ON SNOW: drain-down, dry
    (22, 30,     47.0,   0.00),   # FULL MELT: packs go to zero, then thin tail
]


def phase_at(day):
    for lo, hi, air, rain in PHASES:
        if lo <= day <= hi:
            return air, rain
    return PHASES[-1][2], PHASES[-1][3]


def series(name):
    """Emit one TIMESERIES as (line, air_F, rain_inhr) rows."""
    out = []
    for i in range(N + 1):
        h = i * STEP_H
        day = h // 24 + 1
        hh = h % 24
        # dates roll into January only; DAYS=30 keeps us inside the month.
        date = "01/%02d/2026" % min(day, 31)
        air, rain = phase_at(day)
        out.append((date, "%02d:00" % hh, air, rain))
    return out


rows = series("met")

L = []
w = L.append

w("[TITLE]")
w("Snow parity deck -- the corpus deck the 14 did not have.")
w("Generated by tests/parity/snow/gen_snow_parity.py; do not hand-edit.")
w("Exercises F1-F7 of plans/transport/SNOW_DIVERGENCE_REGISTER.md.")
w("")
w("[OPTIONS]")
w("FLOW_UNITS           CFS")
w(";; KINWAVE, not DYNWAVE. Routing is not what this deck observes, and the")
w(";; dynamic-wave solver costs ~43,000 routing steps and 90 s of wall clock")
w(";; over 30 days here -- measured -- which is too expensive for a deck that")
w(";; runs in every round's bit-identity sweep. Kinematic wave is")
w(";; deterministic, cheap, and leaves the hydrology identical.")
w("FLOW_ROUTING         KINWAVE")
w("INFILTRATION         HORTON")
w("START_DATE           " + START)
w("START_TIME           00:00:00")
w("REPORT_START_DATE    " + START)
w("REPORT_START_TIME    00:00:00")
w("END_DATE             01/31/2026")
w("END_TIME             00:00:00")
w("WET_STEP             01:00:00")
w("DRY_STEP             01:00:00")
w("ROUTING_STEP         300")
w("REPORT_STEP          01:00:00")
w("ALLOW_PONDING        NO")
w("")
w("[EVAPORATION]")
w(";; Zero and constant on purpose: evaporation is not what this deck is")
w(";; about, and a nonzero rate would put a second sink in the balance.")
w("CONSTANT             0.0")
w("DRY_ONLY             NO")
w("")
w("[TEMPERATURE]")
w(";; SNOWMELT -- READ THIS BEFORE EDITING THE LINE BELOW.")
w(";; This engine accepts TWO layouts and disambiguates ONLY by token count")
w(";; (HydrologyHandler.cpp:258):")
w(";;   7 tokens ->  SNOWMELT divT ATIwt nrgRatio LAT minMelt maxMelt")
w(";;   9 tokens ->  SNOWMELT divT ATIwt nrgRatio ELEV LAT DTLONG minMelt maxMelt")
w(";; So the 4th value is LATITUDE in the short form and ELEVATION in the")
w(";; long one. Writing EPA's 6-value line here silently lands elevation in")
w(";; latitude -- verified: a 7-token line with 500.0 in slot 4 reports")
w(";; latitude 500. The long form is used below so every field is explicit.")
w(";; minMelt/maxMelt are stored and round-tripped by InpWriter but read by")
w(";; no solver; 0.0 is the inert value.")
w(";; divT 34 F is the rain/snow dividing temperature: phases 1 and 3 sit")
w(";; below it (precip arrives as snow), phase 4 above it (as rain).")
w("TIMESERIES           air_ts")
w(";;                   divT  ATIwt  nrg   elev   lat   dtlong  minM  maxM")
w("SNOWMELT             34.0  0.5    0.6   500.0  42.0  0.0     0.0   0.0")
w(";; A GRADED areal depletion curve. The engine default is all ones --")
w(";; 'no depletion at any index' -- so without this row SD100 alone still")
w(";; gives full cover and F6/F7 stay unobservable (S4 handoff 9.2).")
w("ADC IMPERVIOUS       0.10 0.25 0.40 0.55 0.68 0.78 0.86 0.92 0.96 1.00")
w("ADC PERVIOUS         0.05 0.18 0.32 0.46 0.60 0.72 0.82 0.90 0.96 1.00")
w("WINDSPEED MONTHLY    10.0 10.0 10.0 10.0 10.0 10.0 10.0 10.0 10.0 10.0 10.0 10.0")
w("")
w("[RAINGAGES]")
w(";;Name  Format     Interval  SCF   Source")
w("RG1     INTENSITY  3:00      1.0   TIMESERIES rain_ts")
w("")
w("[SNOWPACKS]")
w(";;Name    Surface     Cmin   Cmax   Tbase  FWF   SD0     FW0    SD100/SNN0")
w(";;")
w(";; SP_DEEP -- the WATER BALANCE pack (F2, F4, F5).")
w(";; FW0 = 0: it starts UNRIPE, with capacity to spare. That is the regime")
w(";; F2 and F4 lived in and the one three of S3's four gates could not see,")
w(";; because a pack that starts at capacity drains every drop instantly and")
w(";; 'SWE -= melt' and 'SWE -= excess' become the same number.")
w(";; SNN0 = 0.25 on the PLOWABLE row plus the REMOVAL row below make")
w(";; plowSnow live -- the path S2b's published transfer will run through.")
w("SP_DEEP  PLOWABLE    0.002  0.006  32.0   0.10  4.0     0.0    0.25")
w("SP_DEEP  IMPERVIOUS  0.002  0.006  32.0   0.10  4.0     0.0    0.0")
w("SP_DEEP  PERVIOUS    0.001  0.003  32.0   0.05  4.0     0.0    0.0")
w(";;       REMOVAL     Dplow  Fout   Fimp   Fperv Fimelt  Fsub")
w("SP_DEEP  REMOVAL     2.0    0.20   0.10   0.10  0.10    0.0")
w(";;")
w(";; SP_ADC -- the AREAL DEPLETION pack (F6, F7, and F3's rain split).")
w(";; SD0 = 2.0 against SD100 = 8.0: the pack starts BELOW its SD100. That is")
w(";; the exact condition F7 hides behind -- while si was pinned to the")
w(";; initial depth, wsnow >= si fired on step 1 and THAT branch sets")
w(";; awe = 1.0 itself, so a pack starting below SD100 never takes it.")
w("SP_ADC   PLOWABLE    0.002  0.006  32.0   0.10  2.0     0.0    0.0")
w("SP_ADC   IMPERVIOUS  0.002  0.006  32.0   0.10  2.0     0.0    8.0")
w("SP_ADC   PERVIOUS    0.001  0.003  32.0   0.05  2.0     0.0    8.0")
w("SP_ADC   REMOVAL     0.0    0.0    0.0    0.0   0.0     0.0")
w(";;")
w(";; SP_THIN -- the INSTANT MELT pack (F5). SD0 is below the 0.001 in")
w(";; threshold, so the sub-threshold branch fires on the first warm step.")
w(";; Its water used to be written into imelt and then assigned over.")
w("SP_THIN  PLOWABLE    0.002  0.006  32.0   0.10  0.0005  0.0    0.0")
w("SP_THIN  IMPERVIOUS  0.002  0.006  32.0   0.10  0.0005  0.0    0.0")
w("SP_THIN  PERVIOUS    0.001  0.003  32.0   0.05  0.0005  0.0    0.0")
w("SP_THIN  REMOVAL     0.0    0.0    0.0    0.0   0.0     0.0")
w("")
w("[SUBCATCHMENTS]")
w(";;Name    Gage  Outlet  Area  %Imperv  Width  Slope  CurbLen  SnowPack")
w("SUB_DEEP  RG1   J1      5.0   60.0     500.0  0.5    0        SP_DEEP")
w("SUB_ADC   RG1   J1      5.0   40.0     500.0  1.0    0        SP_ADC")
w("SUB_THIN  RG1   J1      5.0   50.0     500.0  0.5    0        SP_THIN")
w(";; A pack-less subcatchment on a project that HAS packs. Without it the")
w(";; only bare deck is a bare PROJECT, where IGNORE_SNOWMELT is forced on")
w(";; (PostParseResolver.cpp:2199, legacy project.c:221) -- so this is the")
w(";; only way to exercise the PER-SUBCATCHMENT no-pack guard.")
w("SUB_BARE  RG1   J1      5.0   50.0     500.0  0.5    0        *")
w("")
w("[SUBAREAS]")
w(";;Subcatch  Nimp   Nperv  Simp  Sperv  %Zero  RouteTo")
for s in ("SUB_DEEP", "SUB_ADC", "SUB_THIN", "SUB_BARE"):
    w("%-10s 0.01   0.10   0.02  0.02   25     OUTLET" % s)
w("")
w("[INFILTRATION]")
w(";;Subcatch  MaxRate  MinRate  Decay  DryTime  MaxInfil")
for s in ("SUB_DEEP", "SUB_ADC", "SUB_THIN", "SUB_BARE"):
    w("%-10s 3.0      0.5      4      7        0" % s)
w("")
w("[JUNCTIONS]")
w(";;Name  Elev  MaxDepth  InitDepth  SurDepth  Aponded")
w("J1      10.0  10.0      0          0         0")
w("")
w("[OUTFALLS]")
w(";;Name  Elev  Type  Gated")
w("OUT     9.0   FREE  NO")
w("")
w("[CONDUITS]")
w(";;Name  From  To   Length  N      Z1  Z2")
w("C1      J1    OUT  400.0   0.013  0   0")
w("")
w("[XSECTIONS]")
w(";;Link  Shape     G1   G2  G3  G4  Barrels")
w("C1      CIRCULAR  3.0  0   0   0   1")
w("")
w("[TIMESERIES]")
w(";; Flat holds inside each phase, stepped at phase boundaries -- so any")
w(";; movement in the output attributes to a phase, not to interpolation.")
for date, hm, air, rain in rows:
    w("air_ts   %s %s  %.1f" % (date, hm, air))
w("")
for date, hm, air, rain in rows:
    w("rain_ts  %s %s  %.2f" % (date, hm, rain))
w("")
w("[COORDINATES]")
w(";;Node  X      Y")
w("J1      0.0    0.0")
w("OUT     400.0  0.0")
w("")
w("[REPORT]")
w("INPUT       NO")
w("CONTROLS    NO")
w("SUBCATCHMENTS ALL")
w("NODES       ALL")
w("LINKS       ALL")
w("")

sys.stdout.write("\n".join(L))
