! Generates the SIR epidemic reference trajectory using the Flash-X
! CashKarp45 ODE integrator.  Writes the reference.csv for the
! openswmm odesolve-sir-epidemic manufactured benchmark.
!
! Build and run:
!   make
!   make run        (writes directly to the benchmark reference.csv)
!   ./generate_sir_reference > <path>/reference.csv
!
program sir_driver
  use RungeKutta_interface, only: RungeKutta_init,             &
                                   RungeKutta_step,            &
                                   RungeKutta_finalize,        &
                                   RungeKutta_stepSizeEstimate
  implicit none

  interface
    function sir_ode(t, y)
      real, intent(in) :: t
      real, intent(in) :: y(:)
      real             :: sir_ode(1:size(y))
    end function sir_ode
  end interface

  integer, parameter :: NVAR   = 3
  real,    parameter :: T_END  = 120.0
  real,    parameter :: DT_OUT = 10.0
  real,    parameter :: E_FRAC = 1.0e-12  ! tighter than openswmm test rtol (1e-6)
  real,    parameter :: H_MAX  = 1.0

  real :: y(NVAR), yout(NVAR), eout(NVAR), eBase(NVAR)
  real :: t, t_next, htry, hused, hnext
  integer :: iout

  call RungeKutta_init()

  y(1) = 0.99   ! S
  y(2) = 0.01   ! I
  y(3) = 0.00   ! R
  t    = 0.0
  eBase = 1.0   ! all compartments O(1)

  write(*, '(a)') '# SIR epidemic reference trajectory'
  write(*, '(a)') '# Generated by Flash-X RungeKutta CashKarp45, eFrac=1e-12 (see provenance.yaml)'
  write(*, '(a)') '# Parameters: beta=0.3/s, gamma=0.1/s, N=1, S(0)=0.99, I(0)=0.01, R(0)=0'
  write(*, '(a)') '# Columns: t_s, S, I, R'
  write(*, '(a)') 't_s,S,I,R'

  write(*, '(f6.1,3(",",f20.15))') t, y(1), y(2), y(3)

  htry = RungeKutta_stepSizeEstimate('CashKarp45', sir_ode, t, y, E_FRAC, eBase, hmax=H_MAX)

  do iout = 1, int(T_END / DT_OUT)
    t_next = real(iout) * DT_OUT

    do while (t < t_next - epsilon(t))
      if (t + htry > t_next) htry = t_next - t

      call RungeKutta_step('CashKarp45', sir_ode, t, y, E_FRAC, eBase, &
                            htry, hused, hnext, yout, eout)
      y    = yout
      t    = t + hused
      htry = hnext
    end do

    write(*, '(f6.1,3(",",f20.15))') t_next, y(1), y(2), y(3)
  end do

  call RungeKutta_finalize()
end program sir_driver
