name: Build for Release

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]
  release:
    types: [created]
    branches:
      - master
      - develop
      - release
jobs:
  build_and_deploy_binaries:

    name: Building Binaries for Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
  build_and_deploy_python:
    name: Building Python Bindings for Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install cmake
    - name: Build and all versions using cibuidwheel
      run: |
        python -m build --sdist
        python -m pip install cibuildwheel
        cibuildwheel --output-dir wheelhouse
    - name: Upload Python Package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages: wheelhouse/*.whl
        repository_url: https://upload.pypi.org/legacy/
        skip_existing: true
  
  build_swmm_docs:
    name: Building and Deploying WMM Docs
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        cname: swmm5-python.readthedocs.io
        commit_message: ${{ github.event.head_commit.message }}
        user_name: ${{ github.event.head_commit.author.name }}
        user_email: ${{ github.event.head_commit.author.email }}
        allow_empty_commit: true
        keep_files: true
        clean: true
        force_orphan: true
        enable_jekyll: true
        jekyll_build_opts: --config _config.yml,_config_dev.yml
        enable_cache: true
        cache_ignore: 'node_modules'

  build_and_deploy_python_docs:
    name: Building and Deploying Python Docs
    depends-on: [build_python]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        cname: swmm5-python.readthedocs.io
        commit_message: ${{ github.event.head_commit.message }}
        user_name: ${{ github.event.head_commit.author.name }}
        user_email: ${{ github.event.head_commit.author.email }}
        allow_empty_commit: true
        keep_files: true
        clean: true
        force_orphan: true
        enable_jekyll: true
        jekyll_build_opts: --config _config.yml,_config_dev.yml
        enable_cache: true
        cache_ignore: 'node_modules